const data = [
  {
    Countries: [
      {
        Country: 'Afghanistan',
        CountryCode: 'AF',
        Slug: 'afghanistan',
        NewConfirmed: 286,
        TotalConfirmed: 34194,
        NewDeaths: 14,
        TotalDeaths: 971,
        NewRecovered: 35,
        TotalRecovered: 20882,
        Date: '2020-07-11T22:07:37Z',
        Premium: {},
      },
      {
        Country: 'Albania',
        CountryCode: 'AL',
        Slug: 'albania',
        NewConfirmed: 90,
        TotalConfirmed: 3278,
        NewDeaths: 2,
        TotalDeaths: 85,
        NewRecovered: 43,
        TotalRecovered: 1875,
        Date: '2020-07-11T22:07:37Z',
        Premium: {},
      },
      {
        Country: 'Algeria',
        CountryCode: 'DZ',
        Slug: 'algeria',
        NewConfirmed: 434,
        TotalConfirmed: 18242,
        NewDeaths: 8,
        TotalDeaths: 996,
        NewRecovered: 487,
        TotalRecovered: 13124,
        Date: '2020-07-11T22:07:37Z',
        Premium: {},
      },
      {
        Country: 'Andorra',
        CountryCode: 'AD',
        Slug: 'andorra',
        NewConfirmed: 0,
        TotalConfirmed: 855,
        NewDeaths: 0,
        TotalDeaths: 52,
        NewRecovered: 1,
        TotalRecovered: 803,
        Date: '2020-07-11T22:07:37Z',
        Premium: {},
      },
      {
        Country: 'Angola',
        CountryCode: 'AO',
        Slug: 'angola',
        NewConfirmed: 62,
        TotalConfirmed: 458,
        NewDeaths: 1,
        TotalDeaths: 23,
        NewRecovered: 0,
        TotalRecovered: 117,
        Date: '2020-07-11T22:07:37Z',
        Premium: {},
      },
      {
        Country: 'Antigua and Barbuda',
        CountryCode: 'AG',
        Slug: 'antigua-and-barbuda',
        NewConfirmed: 1,
        TotalConfirmed: 74,
        NewDeaths: 0,
        TotalDeaths: 3,
        NewRecovered: 0,
        TotalRecovered: 57,
        Date: '2020-07-11T22:07:37Z',
        Premium: {},
      },
      {
        Country: 'Argentina',
        CountryCode: 'AR',
        Slug: 'argentina',
        NewConfirmed: 3367,
        TotalConfirmed: 94060,
        NewDeaths: 54,
        TotalDeaths: 1774,
        NewRecovered: 671,
        TotalRecovered: 38984,
        Date: '2020-07-11T22:07:37Z',
        Premium: {},
      },
      {
        Country: 'Armenia',
        CountryCode: 'AM',
        Slug: 'armenia',
        NewConfirmed: 557,
        TotalConfirmed: 30903,
        NewDeaths: 11,
        TotalDeaths: 546,
        NewRecovered: 709,
        TotalRecovered: 18709,
        Date: '2020-07-11T22:07:37Z',
        Premium: {},
      },
      {
        Country: 'Australia',
        CountryCode: 'AU',
        Slug: 'australia',
        NewConfirmed: 179,
        TotalConfirmed: 9553,
        NewDeaths: 1,
        TotalDeaths: 107,
        NewRecovered: 157,
        TotalRecovered: 7733,
        Date: '2020-07-11T22:07:37Z',
        Premium: {},
      },
      {
        Country: 'Austria',
        CountryCode: 'AT',
        Slug: 'austria',
        NewConfirmed: 94,
        TotalConfirmed: 18709,
        NewDeaths: 0,
        TotalDeaths: 706,
        NewRecovered: 50,
        TotalRecovered: 16808,
        Date: '2020-07-11T22:07:37Z',
        Premium: {},
      },
    ],
    Date: '2020-07-11T22:07:37Z',
  },
];

export default data;
